version: '3.7'

networks:
  elk:
    
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.9.2
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
      
#  logstash:
#    image: logstash:7.9.2
#    ports:
#      - "9600:9600"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch
#    command: logstash -f /usr/share/logstash/pipeline/Calculator_logger_logstash.conf
#    volumes:
#      - type: bind
#        source: ./
#        target: /usr/share/logstash/pipeline
#        read_only: true